# Generated by Django 5.2.1 on 2025-05-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=-2029, upload_to='img'),
            preserve_default=False,
        ),
    ]
